default_install_hook_types:
 [pre-commit, pre-push, commit-msg, prepare-commit-msg]

repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
     - id: pretty-format-java
       args: [--autofix, --google-java-formatter-version=1.21.0]

- repo: https://github.com/zodgevaibhav/pre-commit-hooks
  rev: main
  hooks:
     - id: check_commit_type_scope
       stages: [commit-msg]

- repo: local
  hooks:
      - id: check_commiter_email_id
        name: Check committer email id
        entry: python check_email_domain.py
        language: python
        stages: [pre-commit]

- repo: local
  hooks:
      - id: check_commiter_name
        name: Check committer name
        entry: python check_name_domain.py
        language: python
        stages: [pre-commit]
